// This file is automatically generated from constants.ts
// Do not edit this file directly

export const QUIZ_QUESTIONS = [
  {
    id: 'q-initial-1',
    questionText: "Что такое VSL (Video Sales Letter)?",
    options: [
      "Короткий рекламный ролик для ТВ",
      "Видео-отзыв от клиента",
      "Длинное видео, имитирующее процесс личной продажи для убеждения зрителя",
      "Обучающий вебинар в прямом эфире"
    ],
    correctAnswerIndex: 2,
    explanation: "VSL — это видеоформат, созданный для того, чтобы подробно рассказать о продукте и убедить зрителя в необходимости покупки, имитируя процесс персональной продажи."
  },
  {
    id: 'q-initial-2',
    questionText: "Какова главная цель элитного VSL-монтажера?",
    options: [
      "Нарезать красивые кадры под дикторский голос",
      "Научиться писать продающие тексты",
      "Просто собрать видео в единое целое",
      "Продать, управляя эмоциями зрителя"
    ],
    correctAnswerIndex: 3,
    explanation: "Главное отличие в цели: не просто 'собрать видео', а 'продать'. Элитный VSL-монтажер — это психолог и режиссер, который усиливает текст и управляет эмоциями для достижения продажи."
  },
  // The rest of the questions are omitted for brevity
  // In a real implementation, all questions would be included
];
