version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - CACHE_BUSTER=${CACHE_BUSTER}
    ports:
      - "9753:80"  # Возвращаем предыдущий порт для фронтенда
    restart: always  # Изменено на always для автоматического перезапуска
    depends_on:
      - backend
    networks:
      quiz-network:
        # Без явного приоритета, так как это не критично для фронтенда
    environment:
      - BACKEND_URL=http://backend:8080
    labels:
      - "com.creo-quiz.description=Frontend service for Quiz application"
      - "com.creo-quiz.service=frontend"

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "9754:8080"  # Возвращаем предыдущий порт для бэкенда
    restart: always  # Изменено на always для автоматического перезапуска
    volumes:
      - quiz-data:/app/data  # Исправлен путь к тому
    networks:
      quiz-network:
        # Без явного приоритета, так как это не критично для бэкенда
    environment:
      - PORT=8080
      - NODE_ENV=production
    labels:
      - "com.creo-quiz.description=Backend service for Quiz application"
      - "com.creo-quiz.service=backend"

networks:
  quiz-network:
    name: creo-quiz-network  # Явное именование сети для предсказуемости в Portainer
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16  # Явное указание подсети для предсказуемой адресации
    labels:
      - "com.creo-quiz.description=Network for Quiz application services"

volumes:
  quiz-data:
    name: creo-quiz-data  # Явное именование тома для предсказуемости в Portainer
    labels:
      - "com.creo-quiz.description=Data volume for Quiz application"
    driver: local