version: '3'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - quiz-network
    environment:
      - BACKEND_URL=http://backend:8080

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - quiz-data:/usr/src/app/data
    networks:
      - quiz-network
    environment:
      - PORT=8080
      - NODE_ENV=production

networks:
  quiz-network:
    driver: bridge

volumes:
  quiz-data:
    driver: local