version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "9753:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quiz-network
    environment:
      - BACKEND_URL=http://backend:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3002:3001"
    restart: unless-stopped
    volumes:
      - quiz-data:/usr/src/app/data
    networks:
      - quiz-network
    environment:
      - PORT=3001
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health" , "||" , "exit" , "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

networks:
  quiz-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  quiz-data:
    driver: local